### PR TITLE
Various improvements, updated libraries and image features

### PR DESCRIPTION
**Pull request by Emulator000**
In this PR I updated all libraries, applied various code improvements, fixed tests in case of non enabled `chrono` feature and done some enrichments on the `embed_image` feature, now supports buffers.

I also added an useful function for the `Document` struct called `get_object_page()`, this function will return the Page `ObjectId` if found, useful for inserting certain element of another dependent `ObjectId` and another useful `remove_object()` function that is able to correctly remove an object from the page and the reference.

I also formatted the code with `cargo fmt` in order to be compliant to all Rust 2018 rules.

@J-F-Liu please wait before merging this, I'll to check if the `embed_image` is working properly because I think that is a little buggy. Maybe is not well tested as is not a default feature :-)

### CODE REVIEW

**Comment by Emulator000** [comment]
@J-F-Liu you can now review and merge now!

I've fixed a failing test on the CI, everything should be ok :)

Let me know when you will `cargo publish` it in order to immediately use it on my project, thank you!

**Comment by J-F-Liu** [comment]
Package version should be 0.26.0

**Comment by Emulator000** [comment]
@J-F-Liu done, changed to 0.26 :-)

Please let me know when you'll publish it, thanks!

**Comment by J-F-Liu** [comment]
Published just now.

**Pull request merged**
